### ISSUE TITLE
Header -> Practice -> Youtube Link is broken

### ISSUE THREAD

**Issue by jimmy-liao-gogoro** [aNyMoRe0505/official-site#10]
## Environment
Google Chrome Version 86.0.4240.193 (Official Build) (x86_64)

## Scenario
**Given** user is in this website
**And** user hovers Header -> Practice menu
**When** user click Youtube link

### Actual Result
**Then** Front-end directs to https://anymore0505.github.io/official-site/practice/youtube
**And** webpage is white
**And** user clicks back button
**And** webpage is white, too

### Expected Result
**Then** User can read Youtube content

## Screenshot
![Screen Shot 2020-11-17 at 9 16 21 AM](https://user-images.githubusercontent.com/52391190/99327744-8fb30d80-28b5-11eb-99ec-46a38540d5d1.png)

**Comment by aNyMoRe0505** [comment]
fixed, thanks!

**Comment by jimmy-liao-gogoro** [comment]
I can't search by this search bar.
![Screen Shot 2020-11-19 at 3 00 45 PM](https://user-images.githubusercontent.com/52391190/99632342-0435aa00-2a78-11eb-9adc-8d986937884e.png)

**Comment by aNyMoRe0505** [comment]
@jimmy-liao-gogoro 
Because Youtube API is not free anymore XD
